const rowsTable = [
  {
    id: 1,
    availableBuses: 5,
    depLocation: "Walt Disney Wordl",
    depDate: "6:00 AM",
    arrLocation: "Lake Worth/West Palm Beach",
    arrDate: "9:40 AM",
  },
  {
    id: 2,
    availableBuses: 10,
    depLocation: "Universal Studios Florida",
    depDate: "6:30 AM",
    arrLocation: "Fort Laudedale/Pompano Beach",
    arrDate: "10:00 AM",
  },
  {
    id: 3,
    availableBuses: 8,
    depLocation: "Orlando Terminal",
    depDate: "7:00 AM",
    arrLocation: "Hollywood/Ft.Lauderdale",
    arrDate: "10:40 AM",
  },
  {
    id: 4,
    availableBuses: 9,
    depLocation: "Kissimmee, Walmart Parking",
    depDate: "7:15 AM",
    arrLocation: "North MIami Beach",
    arrDate: "11:30 AM",
  },
  {
    id: 5,
    availableBuses: 12,
    depLocation: "Fort Pierce Plaza",
    depDate: "8:45 AM",
    arrLocation: "South Miami Beach",
    arrDate: "11:50 AM",
  },
];